apiVersion: v1
kind: Service
metadata:
  name: spark-cr-exporter
  namespace: default
  labels:
    app: spark-cr-exporter
spec:
  selector:
    app: spark-cr-exporter
  ports:
  - name: metrics
    port: 9302
    targetPort: 9302
    protocol: TCP
  type: ClusterIP
